version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=todolist.settings
    command: python todolist/manage.py runserver 0.0.0.0:8000 
